import { Document } from 'mongoose';

// Interface for Category document (used for TypeScript type definitions)
export interface ICategory extends Document {
  _id: string; // Category ID generated by MongoDB
  name: string; // Name of the category (e.g., CT Scan, MRI, etc.)
  description?: string; // Optional description of the category
  createdAt?: Date; // Timestamp when the category was created
  updatedAt?: Date; // Timestamp when the category was last updated
}

// Interface for paginated categories (for APIs that return paginated results)
export interface PaginatedCategories {
  categories: ICategory[]; // Array of category documents
  totalPages: number; // Total number of pages for pagination
  currentPage: number; // Current page number
}


